#!/bin/bash
# A simple wrapper for gh-pages_push.rb
# Created to handle the passing of proper arguments to ruby (b/c it was having trouble finding the gem: grancher)
# Should be called from branch with the autogenerated doc.
echo "calling gh-pages_push.rb"
ruby -rubygems gh-pages_push.rb

